language: shell

jobs:
  include:
    - name: Debian 10 buster (amd64)
      os: linux
      env:
        - DEBIAN_RELEASE: buster
        - DEBIAN_ARCH: amd64
      services:
        - docker

    - name: Debian 10 buster (i386)
      os: linux
      env:
        - DEBIAN_RELEASE: buster
        - DEBIAN_ARCH: i386
      services:
        - docker

    - name: Debian 10 buster (arm64)
      os: linux
      arch: arm64
      env:
        - DEBIAN_RELEASE: buster
        - DEBIAN_ARCH: arm64
      services:
        - docker

    - name: Debian 10 buster (armhf)
      os: linux
      env:
        - DEBIAN_RELEASE: buster
        - DEBIAN_ARCH: armhf
      services:
        - docker

    - name: Debian 10 buster (mips64el)
      os: linux
      env:
        - DEBIAN_RELEASE: buster
        - DEBIAN_ARCH: mips64el
      services:
        - docker
        

before_install:
  - if [ "$DEBIAN_ARCH" != amd64 ]; then docker run --rm --privileged multiarch/qemu-user-static:register --reset; fi
  - docker build -t docker-deb-builder:${DEBIAN_RELEASE}-${DEBIAN_ARCH} -f docker-deb-builder/Dockerfile-debian-${DEBIAN_RELEASE}-${DEBIAN_ARCH} .

  
install:
  - ./scan-and-build.sh

script:
  - ./summary.sh
